apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example-deployment
spec:
  selector:
    matchLabels:
      app: aks-sample-linux-app
  template:
    metadata:
      labels:
        app: aks-sample-linux-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aks-sample-linux-service
spec:
  type: LoadBalancer
  selector:
    app: aks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80